name: amin_agent
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_svg: 
  confetti: 
  cached_network_image: 
  connectivity_plus: 
  google_maps_flutter: 
  location: 
  http: 
  material_dialogs: 
  pin_code_fields: 
  device_preview: 
  readmore: 
  responsive_sizer: 
  circular_profile_avatar: 
  fl_chart: 
  badges: 
  get_storage: 
  bottom_bar_matu: 
  panara_dialogs: 
  calendar_date_picker2: 
  intl: ^0.19.0
  bottom_navy_bar: ^6.1.0
  image_picker: ^1.1.2


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
        - asset: assets/fonts/rubik/Rubik-Black.ttf
        - asset: assets/fonts/rubik/Rubik-BlackItalic.ttf
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
        - asset: assets/fonts/rubik/Rubik-BoldItalic.ttf
        - asset: assets/fonts/rubik/Rubik-ExtraBold.ttf
        - asset: assets/fonts/rubik/Rubik-ExtraBoldItalic.ttf
        - asset: assets/fonts/rubik/Rubik-Light.ttf
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
        - asset: assets/fonts/rubik/Rubik-SemiBoldItalic.ttf
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          style: Regular